/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controller.AlumnosModel;
import controller.Controlador;
import javax.swing.JOptionPane;
import objects.Alumno;

/**
 *
 * @author karimnot
 */
public class AlumnosFrame extends javax.swing.JFrame {

    
    private Controlador controlador;
    private AlumnosModel modelo;
    
    private AcercaDialog acercaDialog;
    private AlumnoDialog alumnoDialog;
    /**
     * Creates new form AlumnosFrame
     */
    public AlumnosFrame() {
        
        controlador = new Controlador();
        modelo = new AlumnosModel(controlador.obtenerAlumnos());
        
        acercaDialog = new AcercaDialog(this, true);
        alumnoDialog = new AlumnoDialog(this, true);
        alumnoDialog.setControlador(controlador);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        alumnosTable = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        nuevotool = new javax.swing.JButton();
        actualizarTool = new javax.swing.JButton();
        eliminarTool = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        guardarTool = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        ayudaTool = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        salirTool = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        nuevoMenu = new javax.swing.JMenuItem();
        modificarMenu = new javax.swing.JMenuItem();
        eliminarMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        guardarMenu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        salirMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ayudaMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        alumnosTable.setModel(modelo);
        jScrollPane1.setViewportView(alumnosTable);

        jToolBar1.setRollover(true);

        nuevotool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new.png"))); // NOI18N
        nuevotool.setFocusable(false);
        nuevotool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevotool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nuevotool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoMenuActionPerformed(evt);
            }
        });
        jToolBar1.add(nuevotool);

        actualizarTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        actualizarTool.setFocusable(false);
        actualizarTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        actualizarTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        actualizarTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarMenuActionPerformed(evt);
            }
        });
        jToolBar1.add(actualizarTool);

        eliminarTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        eliminarTool.setFocusable(false);
        eliminarTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eliminarTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eliminarTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarMenuActionPerformed(evt);
            }
        });
        jToolBar1.add(eliminarTool);
        jToolBar1.add(jSeparator4);

        guardarTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        guardarTool.setFocusable(false);
        guardarTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guardarTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        guardarTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarMenuActionPerformed(evt);
            }
        });
        jToolBar1.add(guardarTool);
        jToolBar1.add(jSeparator5);

        ayudaTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png"))); // NOI18N
        ayudaTool.setFocusable(false);
        ayudaTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ayudaTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ayudaTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaMenuActionPerformed(evt);
            }
        });
        jToolBar1.add(ayudaTool);
        jToolBar1.add(jSeparator3);

        salirTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        salirTool.setFocusable(false);
        salirTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salirTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salirTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuActionPerformed(evt);
            }
        });
        jToolBar1.add(salirTool);

        jMenu1.setText("Archivo");

        nuevoMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        nuevoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new.png"))); // NOI18N
        nuevoMenu.setText("Nuevo alumno");
        nuevoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoMenuActionPerformed(evt);
            }
        });
        jMenu1.add(nuevoMenu);

        modificarMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        modificarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        modificarMenu.setText("Modificar...");
        modificarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarMenuActionPerformed(evt);
            }
        });
        jMenu1.add(modificarMenu);

        eliminarMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        eliminarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        eliminarMenu.setText("Eliminar");
        eliminarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarMenuActionPerformed(evt);
            }
        });
        jMenu1.add(eliminarMenu);
        jMenu1.add(jSeparator1);

        guardarMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        guardarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        guardarMenu.setText("Guardar");
        guardarMenu.setToolTipText("");
        guardarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarMenuActionPerformed(evt);
            }
        });
        jMenu1.add(guardarMenu);
        jMenu1.add(jSeparator2);

        salirMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.META_MASK));
        salirMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        salirMenu.setText("Salir");
        salirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuActionPerformed(evt);
            }
        });
        jMenu1.add(salirMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        ayudaMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        ayudaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png"))); // NOI18N
        ayudaMenu.setText("Acerca de...");
        ayudaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaMenuActionPerformed(evt);
            }
        });
        jMenu2.add(ayudaMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoMenuActionPerformed
        System.out.println("Nuevo");
        alumnoDialog.setVisible(true);
        modelo.fireTableDataChanged();
        System.out.println("Cerro");
    }//GEN-LAST:event_nuevoMenuActionPerformed

    private void salirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuActionPerformed
        System.out.println("Salir");
        salirAction();
    }//GEN-LAST:event_salirMenuActionPerformed

    private void ayudaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaMenuActionPerformed
        System.out.println("Ayuda");
        acercaDialog.setVisible(true);
    }//GEN-LAST:event_ayudaMenuActionPerformed

    private void modificarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarMenuActionPerformed
        int selected = alumnosTable.getSelectedRow();
        if (selected > -1){
            Alumno alumno = controlador.obtenerAlumno(selected);
            System.out.println(alumno);
        }else{
            JOptionPane.showMessageDialog(
                    this, 
                    "No has seleccionado a ningun alumno", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_modificarMenuActionPerformed

    private void eliminarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarMenuActionPerformed
        int selected = alumnosTable.getSelectedRow();
        if (selected > -1){
            controlador.eliminar(selected);
            modelo.fireTableDataChanged();
        }else{
            JOptionPane.showMessageDialog(
                    this, 
                    "No has seleccionado a ningun alumno", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_eliminarMenuActionPerformed

    private void guardarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarMenuActionPerformed
        System.out.println("Guaradar");
        controlador.guardar();
    }//GEN-LAST:event_guardarMenuActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        salirAction();
    }//GEN-LAST:event_formWindowClosing

    private void salirAction(){
        int opcion = JOptionPane.showConfirmDialog(
                this, 
                "¿Estas realmente seguro de salir?",
                "Confirmacion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );
        if (opcion == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlumnosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlumnosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlumnosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlumnosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlumnosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarTool;
    private javax.swing.JTable alumnosTable;
    private javax.swing.JMenuItem ayudaMenu;
    private javax.swing.JButton ayudaTool;
    private javax.swing.JMenuItem eliminarMenu;
    private javax.swing.JButton eliminarTool;
    private javax.swing.JMenuItem guardarMenu;
    private javax.swing.JButton guardarTool;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem modificarMenu;
    private javax.swing.JMenuItem nuevoMenu;
    private javax.swing.JButton nuevotool;
    private javax.swing.JMenuItem salirMenu;
    private javax.swing.JButton salirTool;
    // End of variables declaration//GEN-END:variables
}
